name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} '
            rm -rf app &&
            mkdir app
          '
          scp -r ./* ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app/

      - name: SSH into EC2 and run Docker
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} '
            cd app &&
            docker stop mnist-app || true &&
            docker rm mnist-app || true &&
            docker build -t mnist-app . &&
            docker run -d -p 80:8000 --name mnist-app mnist-app
          '
